---
title: "README"
author: ""
date: ""
output:
  github_document: 
    html_preview: true
    df_print: kable
  pdf_document: 
    includes:
      in_header: header.tex
    template: eisvogel.latex
    latex_engine: xelatex
    df_print: kable
titlepage: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE, echo=TRUE}
library(tidyverse)


dat <- read_csv('Data/cpl_and_conversion.csv') %>% as_tibble()


set.seed(1212)
# question 1 --------------------------------------------------------------

calc_profit <- function(x = 1212){
  L <- sample(3000:4000, 30, replace = T)
  R <- rnorm(n = 30, mean = 0.04, sd = 0.005)
  M <- sample(350:400, 30, replace = T)
  H <- 20000
  Cpl <- sample(8:10, 30, replace = T)
  Total_profit <- 0
  
  for (i in 1:30) {
    Income <- L[i] * R[i] * M[i]
    Expenses <- H + Cpl[i] * L[i]
    Profit <- Income - Expenses
    Total_profit <- Profit + Total_profit}
  
  return(Total_profit)
}

trials = 1000
result <- replicate(trials, calc_profit())
result <- result %>% as_tibble() %>% 
  mutate(profits = as.integer(value)) %>% 
  select(profits)
```

## 第一题
```{r cars, echo=TRUE}
result %>% 
  ggplot(aes(profits))+
    geom_density()

print(quantile(result$profits,probs = c(0.025,0.975)))
```
## 第二题
### 概率是
```{r pressure, echo=TRUE}

p_up_10w = nrow(result[which(result$profits >= 100000),])/1000
print(p_up_10w)


```
## 第三题
```{r pressure1, echo=TRUE}

result %>% 
  ggplot(aes(profits))+
  stat_ecdf()


```